/* (c) 2026 Open Source Geospatial Foundation - all rights reserved
 * This code is licensed under the GPL 2.0 license, available at the root
 * application directory.
 */

package org.geofence.core.db;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;
import org.testcontainers.DockerClientFactory;
import org.testcontainers.postgresql.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

/**
 * Shared Postgres/PostGIS Testcontainer for {@code geofence.datasource.*}, framework-agnostic so both JUnit5 (see
 * {@link BaseContainerTest}) and JUnit4 consumers can use it.
 *
 * <p>The container is started lazily, so callers must first skip themselves via {@link #isDockerAvailable()} - a
 * Docker-less environment (Windows CI, for one) would otherwise fail rather than skip.
 */
public final class GeofenceTestDatabase {

    private static final String POSTGRES_IMAGE = "postgis/postgis:15-3.4";
    private static final String POSTGRES_DB = "geofence_test-test";
    private static final String POSTGRES_USER = "geofence_test";
    private static final String POSTGRES_PASSWORD = "geofence_test";
    private static final String DRIVER_CLASS_NAME = "org.postgresql.Driver";

    private static boolean configured;

    /** Holds the container so that merely loading this class does not try to start Docker. */
    private static final class Holder {
        private static final PostgreSQLContainer CONTAINER = start();

        private static PostgreSQLContainer start() {
            PostgreSQLContainer container = new PostgreSQLContainer(
                            DockerImageName.parse(POSTGRES_IMAGE).asCompatibleSubstituteFor("postgres"))
                    .withDatabaseName(POSTGRES_DB)
                    .withUsername(POSTGRES_USER)
                    .withPassword(POSTGRES_PASSWORD);
            container.start();
            return container;
        }
    }

    private GeofenceTestDatabase() {}

    /** Whether Docker can be reached; test classes needing this database must skip themselves when it cannot. */
    public static boolean isDockerAvailable() {
        return DockerClientFactory.instance().isDockerAvailable();
    }

    public static String getJdbcUrl() {
        return Holder.CONTAINER.getJdbcUrl();
    }

    public static String getUsername() {
        return Holder.CONTAINER.getUsername();
    }

    public static String getPassword() {
        return Holder.CONTAINER.getPassword();
    }

    public static String getDriverClassName() {
        return DRIVER_CLASS_NAME;
    }

    /**
     * Writes a {@code geofence-datasource.properties} file pointing at this Testcontainer and points
     * {@code GEOFENCE_DATASOURCE_FILE} at it, exercising the real config-loading path. Starts the container on first
     * call, so check {@link #isDockerAvailable()} first; must run before the application context is refreshed.
     */
    public static synchronized void configureAsDatasourceOverride() {
        if (configured) {
            return;
        }
        Properties props = new Properties();
        props.setProperty("geofence.datasource.url", getJdbcUrl());
        props.setProperty("geofence.datasource.username", getUsername());
        props.setProperty("geofence.datasource.password", getPassword());
        props.setProperty("geofence.datasource.driver", getDriverClassName());

        try {
            Path file = Files.createTempFile("geofence-datasource", ".properties");
            file.toFile().deleteOnExit();
            try (var out = Files.newOutputStream(file)) {
                props.store(out, "Generated by GeofenceTestDatabase");
            }
            System.setProperty("GEOFENCE_DATASOURCE_FILE", file.toAbsolutePath().toString());
            configured = true;
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
